spring:
  datasource:
    url: jdbc:mysql://localhost:3306/storedproducer
    username: root
    password: root

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 8083